force-app/main/default/objects/Workshops__c/Workshops__c.object-meta.xml
<CustomObject>
    <label>Workshops</label>
    <nameField>
        <displayFormat>BZ {0000}</displayFormat>
        <label>Workshops Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workshops</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Workshops__c/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <description>The time the workshop finishes</description>
    <label>End Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Workshops__c/fields/Number_of_Attendees__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Attendees__c</fullName>
    <inlineHelpText>How many people attended the workshop?</inlineHelpText>
    <label>Number of Attendees</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Workshops__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Workshops</relationshipLabel>
    <relationshipName>Workshops</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Workshops__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Workshops</relationshipLabel>
    <relationshipName>Workshops</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Workshops__c/fields/Presenter__c.field-meta.xml
<CustomField>
    <fullName>Presenter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Presenter</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Presenter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Workshops (Presenter)</relationshipLabel>
    <relationshipName>Workshops1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OpportunityOneWeekBeforeCloseDate_Test.cls
/*
Created By          : Girikon (Aman Mahto)
Created On          : Jan 5, 2025
@description        : This is test class of class OpportuintyOneWeekBeforeCloseDate.

Modification log --
Modified By         :
Modified On         :
@description        :
*/

@isTest
public class OpportunityOneWeekBeforeCloseDate_Test {
    
    @TestSetup
    static void testData(){
    
        List<Opportunity> oppList = new List<Opportunity>();
        List<Contact> contactList = new List<Contact>();
        List<OpportunityContactRole> opportunityContactRoleList = new List<OpportunityContactRole>();
        
        Account acc = new Account(Name='testAcc');
        
        insert acc;
        
        for(Integer i=0;i<5;i++){
            
            oppList.add(new Opportunity(Name='opp'+i,closeDate=date.newinstance(2025,1,4),StageName='Prospecting'));
            contactList.add(new Contact(LastName='Con'+i,Email='amanstmarks123@gmail.com',AccountId=acc.Id,Presenter__c=true));
        }
        
        insert oppList;
        insert contactList;
        
        Workshops__c ws1 = new Workshops__c(Organisation__c=acc.Id,Start_Date_Time__c= datetime.newInstance(2025,1,1),End_Date_Time__c=datetime.newInstance(2025,2,1),Presenter__c=contactList[0].Id,Number_of_Attendees__c=6,Opportunity__c=oppList[0].Id);
        Workshops__c ws2 = new Workshops__c(Organisation__c=acc.Id,Start_Date_Time__c= datetime.newInstance(2025,1,1),End_Date_Time__c=datetime.newInstance(2025,2,1),Presenter__c=contactList[1].Id,Number_of_Attendees__c=9,Opportunity__c=oppList[0].Id);
       
        insert ws1;
        insert ws2;
        
        for(Integer i=0;i<3;i++){
            
            opportunityContactRoleList.add(new OpportunityContactRole(ContactId=contactList[0].Id,OpportunityId=oppList[i].Id,IsPrimary=true));	
         }
        
        insert opportunityContactRoleList;    
    }
    
    @isTest
    static void testMailToPrimaryContact(){
         
        List<Opportunity> oppList = [Select Id,Name,CloseDate From Opportunity Where Name Like 'opp%'];
        
        Test.startTest();
        
        System.assertEquals(0, Limits.getEmailInvocations(), 'No emails should be sent');
        
        OpportuintyOneWeekBeforeCloseDate.sendMailToPrimaryContact(new List<List<Opportunity>>{oppList});
        
        System.assertEquals(1, Limits.getEmailInvocations(), 'Emails should be sent');
        
        Test.stopTest();
    }
}