force-app/main/default/objects/Workshops__c/Workshops__c.object-meta.xml
<CustomObject>
    <label>Workshops</label>
    <nameField>
        <displayFormat>BZ {0000}</displayFormat>
        <label>Workshops Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workshops</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Workshops__c/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <description>The time the workshop finishes</description>
    <label>End Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Workshops__c/fields/Number_of_Attendees__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Attendees__c</fullName>
    <inlineHelpText>How many people attended the workshop?</inlineHelpText>
    <label>Number of Attendees</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Workshops__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Workshops</relationshipLabel>
    <relationshipName>Workshops</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Workshops__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Workshops</relationshipLabel>
    <relationshipName>Workshops</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Workshops__c/fields/Presenter__c.field-meta.xml
<CustomField>
    <fullName>Presenter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Presenter</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Presenter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Workshops (Presenter)</relationshipLabel>
    <relationshipName>Workshops1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SendFinalDetailsToSchool_Test.cls
/*
Created By          : Girikon (Sahil)
Created On          : Feb 28, 2025
@description        : This class is a test class for SendFinalDetailsToSchool class.

Modification log --
Modified By         : 
Modified On         : 
@description        : 
*/
@isTest
private class SendFinalDetailsToSchool_Test 
{
    @TestSetup
    static void makeData()
    {
        Account acc = new Account(Name = 'Test Acc');
        INSERT acc;
        Opportunity opp = new Opportunity(Name = 'Test Opp', CloseDate = Date.newinstance(2025,1,4), StageName = 'Prospecting', AccountId = acc.Id);
        INSERT opp;
        Contact con = new Contact(LastName = 'TestCon', Email = 'amanstmarks123@gmail.com', AccountId = acc.Id, Presenter__c = true);
        INSERT con;
        Workshops__c ws1 = new Workshops__c(Organisation__c = acc.Id, Start_Date_Time__c = DateTime.newInstance(2025,1,1), End_Date_Time__c = DateTime.newInstance(2025,2,1), Presenter__c = con.Id, Number_of_Attendees__c = 6, Opportunity__c = opp.Id);
        Workshops__c ws2 = new Workshops__c(Organisation__c = acc.Id, Start_Date_Time__c = DateTime.newInstance(2025,1,1), End_Date_Time__c = DateTime.newInstance(2025,2,1), Presenter__c = con.Id, Number_of_Attendees__c = 9,Opportunity__c = opp.Id);
        INSERT ws1;
        INSERT ws2;
        Quote qt = new Quote(Name = 'Test Quote', OpportunityId = opp.Id, ContactId = con.Id, Status = 'Accepted');  
        INSERT qt;
    }
    @isTest
    static void sendFinalDetailsEmailTest()
    {
        List<Opportunity> oppList = [SELECT Id FROM Opportunity LIMIT 1];
        Test.startTest();
        SendFinalDetailsToSchool.sendFinalDetailsEmail(new List<Id>{oppList[0].Id});
        Test.stopTest();
    }
}