force-app/main/default/objects/Workshops__c/Workshops__c.object-meta.xml
<CustomObject>
    <label>Workshops</label>
    <nameField>
        <displayFormat>BZ {0000}</displayFormat>
        <label>Workshops Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workshops</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Workshops__c/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <description>The time the workshop finishes</description>
    <label>End Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Workshops__c/fields/Number_of_Attendees__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Attendees__c</fullName>
    <inlineHelpText>How many people attended the workshop?</inlineHelpText>
    <label>Number of Attendees</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Workshops__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Workshops</relationshipLabel>
    <relationshipName>Workshops</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Workshops__c/fields/Presentation_Duration_In_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Presentation_Duration_In_Minutes__c</fullName>
    <label>Presentation Duration (In Minutes)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>45</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>90</fullName>
            </value>
            <value>
                <fullName>40</fullName>
                <isActive>false</isActive>
                <label>40</label>
            </value>
            <value>
                <fullName>50</fullName>
                <isActive>false</isActive>
                <label>50</label>
            </value>
            <value>
                <fullName>55</fullName>
                <isActive>false</isActive>
                <label>55</label>
            </value>
            <value>
                <fullName>65</fullName>
                <isActive>false</isActive>
                <label>65</label>
            </value>
            <value>
                <fullName>70</fullName>
                <isActive>false</isActive>
                <label>70</label>
            </value>
            <value>
                <fullName>75</fullName>
                <isActive>false</isActive>
                <label>75</label>
            </value>
            <value>
                <fullName>80</fullName>
                <isActive>false</isActive>
                <label>80</label>
            </value>
            <value>
                <fullName>85</fullName>
                <isActive>false</isActive>
                <label>85</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Workshops__c/fields/Presenter__c.field-meta.xml
<CustomField>
    <fullName>Presenter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Presenter</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Presenter__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Workshops (Presenter)</relationshipLabel>
    <relationshipName>Workshops1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Workshops__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Workshops</relationshipLabel>
    <relationshipName>Workshops</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Workshops__c/fields/Year_Level__c.field-meta.xml
<CustomField>
    <fullName>Year_Level__c</fullName>
    <label>Year Level</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Year_Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportuintyOneWeekBeforeCloseDate.cls
/*
Created By          : Girikon (Aman Mahto)
Created On          : Dec 27, 2024
@description        : This class contains an invocable method which sends mail to Primary contact of each opportunity.Mail contains workshop details related to opportunity and Name of Primary Contact.
Test Class          : OpportunityOneWeekBeforeCloseDate_Test (Coverage: 97%)
 
Modification log --
Modified By         :
Modified On         :
@description        :
*/
public class OpportuintyOneWeekBeforeCloseDate {
    
    @InvocableMethod(label='Mail To PrimaryContact ' description='Send Mail To Primary Contact One Week Before Close Date Of Opportunity ' category='Opportunity')
    public static void sendMailToPrimaryContact(List<List<Opportunity>> opportunityList) {
        
        List<EmailTemplate> etList = [SELECT Id, Subject, HtmlValue FROM EmailTemplate WHERE DeveloperName = 'Email_For_Opportunity_One_Week_Before_Close_Date_1735214901440'];
        String sendersEmail = System.label.Sender_s_Email_Address; 
        List<OrgWideEmailAddress> oweaList = [SELECT Id FROM OrgWideEmailAddress WHERE Address = :sendersEmail];
        List<Messaging.SingleEmailMessage> allmsg = new List<Messaging.SingleEmailMessage>();
        
        Map<Id, String> opportWorkshopstringMap = new Map<Id, String>();
        List<Workshops__c> workshopsList = [SELECT End_Date_Time__c, Number_of_Attendees__c, Presenter__r.Name, Start_Date_Time__c,Program__r.Name, Year_Level__c, Opportunity__r.Id, Presentation_Duration_In_Minutes__c FROM Workshops__c WHERE Opportunity__r.Id IN :opportunityList[0] ORDER BY Start_Date_Time__c];
        List<Opportunity> newOpportList = [SELECT Id,closeDate,(SELECT Id, Presenter__r.Name FROM Workshops__r), (SELECT IsPrimary, ContactId, Contact.Name FROM OpportunityContactRoles WHERE IsPrimary = true) FROM Opportunity WHERE Id IN :opportunityList[0]];
        
        string table = '<table><tr><th style="padding: 3px;">Facilitator Name</th><th style="padding: 3px;">Program Name</th><th style="padding: 3px;">Year Level</th><th style="padding: 3px;">No. of Attendees</th><th style="padding: 3px;">Date</th><th style="padding: 3px;">Time</th><th style="padding: 3px;">Presentation Duration (In Minutes)</th></tr>';
        
        for (Workshops__c wc : workshopsList) {
            
             String temp = '<tr>' + '<td style="padding: 3px;">' + (wc.Presenter__c != null ? wc.Presenter__r.Name : ' ') + '</td>'+ '<td style="padding: 3px;">' + (wc.Program__c != null ? wc.Program__r.Name : ' ') + '</td>' +
                           '<td style="padding: 3px;">' +(wc.Year_Level__c != null ? wc.Year_Level__c : ' ') + '</td>' +'<td style="text-align: center;padding: 3px;">' +(wc.Number_of_Attendees__c != null ? wc.Number_of_Attendees__c :0) + '</td>' + '<td style="padding: 3px;">' + (wc.Start_Date_Time__c != null ?  wc.Start_Date_Time__c.date().format() : ' ') + '</td>' + '<td style="padding: 3px;">' + (wc.Start_Date_Time__c != null ? wc.Start_Date_Time__c.format('h:mm a') : ' ') + '</td>' + '<td style="text-align: center;padding: 3px;">' + (wc.Presentation_Duration_In_Minutes__c != null ? wc.Presentation_Duration_In_Minutes__c : ' ') + '</td>' + '</tr>'; 
                        
            if (!opportWorkshopstringMap.containsKey(wc.Opportunity__r.Id)) {
                
                opportWorkshopstringMap.put(wc.Opportunity__r.Id, temp);
                } 
            else {
                
                opportWorkshopstringMap.put(wc.Opportunity__r.Id, opportWorkshopstringMap.get(wc.Opportunity__r.Id) + temp);
            }
        }
        
        for(Opportunity opp : newOpportList) {
            
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            
            if (!etList.isEmpty()) {
                
                String htmlbody = etList[0].HtmlValue;
                htmlbody = htmlbody.replace('{{{CloseDate}}}',opp.closeDate.format());
                
                if(!opp.OpportunityContactRoles.isEmpty()){
                    
                    htmlbody = htmlbody.replace('{{{ContactName}}}', opp.OpportunityContactRoles[0].Contact.Name);
                    mail.setTargetObjectId(opp.OpportunityContactRoles[0].ContactId);
                    mail.setSaveAsActivity(true);
                }
                
                else{
                    
                    htmlbody = htmlbody.replace('{{{ContactName}}}',' ');
                }
                
                if (opportWorkshopstringMap.containsKey(opp.Id)) {
                    
                    htmlbody = htmlbody.replace('{{{Workshop}}}', table+opportWorkshopstringMap.get(opp.Id)+'</table>');
                    System.debug('Body2' + htmlbody);
               }
                else{
                    
                    htmlbody = htmlbody.replace('{{{Workshop}}}',' ');
                    System.debug('Body2' + htmlbody);
               }
                
                mail.setHtmlBody(htmlbody);
                mail.setSubject(etList[0].Subject);
            }
            
            if (!oweaList.isEmpty()) {
                
                mail.setOrgWideEmailAddressId(oweaList[0].Id);        
            }
            
            allmsg.add(mail);   
        }
        
        try {
            
            Messaging.SendEmailResult[] results = Messaging.sendEmail(allmsg, false);    
        } 
        catch (Exception e) {
            
            System.debug('hi error');
            System.debug('Exception type caught: ' + e.getTypeName());
            System.debug(e.getMessage());     
        }
        
    }
}